version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_create_environment:
      - python -m pip install --force-reinstall --no-deps --no-build-isolation jupyterlite-core==0.9.0a1 jupyterlite-pyodide-kernel==0.9.0a1 jupyterlite-javascript-kernel==0.4.0a5

conda:
  environment: docs/environment.yml

submodules:
  include: all
  recursive: true

sphinx:
   configuration: docs/conf.py
