import { expect, test } from '@jupyterlab/galata';

const INSTALLED_WHEEL_MARKER_ID = 'jp-plugin-playground-wheel-installed-marker';
const INSTALLED_WHEEL_MARKER_TEXT = 'wheel-installed-marker-ready';

function envValue(name: string): string | undefined {
  const processLike = globalThis as {
    process?: { env?: Record<string, string | undefined> };
  };
  return processLike.process?.env?.[name];
}

test.skip(
  envValue('PLAYGROUND_TEST_INSTALLED_WHEEL') !== '1',
  'requires a wheel generated by integration tests and installed with pip'
);

test('installed wheel activates and adds the expected DOM marker', async ({
  page
}) => {
  await page.goto();

  await page.waitForFunction(
    ({ markerId, markerText }) => {
      const marker = document.getElementById(markerId);
      return marker?.textContent === markerText;
    },
    {
      markerId: INSTALLED_WHEEL_MARKER_ID,
      markerText: INSTALLED_WHEEL_MARKER_TEXT
    }
  );

  await expect(page.locator(`#${INSTALLED_WHEEL_MARKER_ID}`)).toHaveText(
    INSTALLED_WHEEL_MARKER_TEXT
  );
});
